name: Check dependency versions
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 05 * * *'
jobs:
  check-dependency-versions:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}

      - name: Extract container base image name/label
        id: base_image
        run: echo "::set-output name=label::$(grep FROM src/Dockerfile | awk '{ print $2 }')"

      - name: Capture dependency info
        run: |
          sudo docker run --rm ${{ steps.base_image.outputs.label }}  bash -c "apt-get -qq update ; apt-get -qq -s satisfy samba samba-vfs-modules smbclient tini | grep ^Inst" >upstream_latest_release.txt

      - name: Fetch FROM docker image
        run: |
          sudo docker pull ${{ steps.base_image.outputs.label }}

      - name: Capture FROM docker image hash
        run: |
          docker images ${{ steps.base_image.outputs.label }} >upstream_docker_version.txt

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")

      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git commit -am "New upstream release"
          git push
