name: Check dependency versions
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 05 * * *'
jobs:
  check-dependency-versions:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}

      - name: Ensure package cache is up to date
        run: |
          sudo apt-get update

      - name: Capture dependency info
        run: |
          apt-get -qq -s satisfy samba samba-vfs-modules smbclient tini | grep ^Inst >upstream_latest_release.txt

      - name: Fetch FROM docker image
        run: |
          sudo docker pull $(grep FROM src/Dockerfile | awk '{ print $2 }')

      - name: Capture FROM docker image hash
        run: |
          docker images $(grep FROM src/Dockerfile | awk '{ print $2 }') >upstream_docker_version.txt

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")

      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git commit -am "New upstream release"
          git push
